# Generated by Django 4.1.6 on 2023-03-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCoreq',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.TextField(blank=True, db_column='Course', null=True)),
                ('coreq', models.TextField(blank=True, db_column='Coreq', null=True)),
            ],
            options={
                'db_table': 'course_coreq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('course', models.TextField(db_column='Course', primary_key=True, serialize=False)),
                ('course_name', models.TextField(blank=True, db_column='Course Name', null=True)),
            ],
            options={
                'db_table': 'course_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoursePrereq',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.TextField(blank=True, db_column='Course', null=True)),
                ('prereq', models.TextField(blank=True, db_column='Prereq', null=True)),
            ],
            options={
                'db_table': 'course_prereq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MajorRequirements',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('degree', models.TextField(blank=True, db_column='Degree', null=True)),
                ('major', models.TextField(blank=True, db_column='Major', null=True)),
                ('course', models.TextField(blank=True, db_column='Course', null=True)),
            ],
            options={
                'db_table': 'major_requirements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject', models.TextField(blank=True, db_column='Subject', null=True)),
                ('subj', models.TextField(db_column='Subj', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'subjects',
                'managed': False,
            },
        ),
    ]
