# Generated by Django 4.1.6 on 2023-02-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_data',
            fields=[
                ('CRN', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=50)),
                ('days', models.CharField(max_length=10, null=True)),
                ('start_time', models.CharField(max_length=10, null=True)),
                ('end_time', models.CharField(max_length=10, null=True)),
                ('room', models.CharField(max_length=10, null=True)),
                ('instructor', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='class_prereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRN', models.IntegerField()),
                ('prereq_CRN', models.IntegerField(null=True)),
            ],
        ),
    ]
