# Generated by Django 4.1.6 on 2023-02-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_data',
            name='building',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
