# Generated by Django 4.1.6 on 2023-02-10 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_class_data_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class_data',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='class_prereq',
            options={'managed': False},
        ),
    ]
