# Generated by Django 4.1.6 on 2023-02-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_class_data_table_alter_class_prereq_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassData',
            fields=[
                ('crn', models.TextField(db_column='CRN', primary_key=True, serialize=False)),
                ('camp', models.TextField(blank=True, db_column='Camp', null=True)),
                ('pot', models.TextField(blank=True, db_column='POT', null=True)),
                ('subj_crs_sec', models.TextField(blank=True, db_column='Subj Crs Sec', null=True)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('crd', models.TextField(blank=True, db_column='Crd', null=True)),
                ('cont_hrs', models.TextField(blank=True, db_column='Cont Hrs', null=True)),
                ('days', models.TextField(blank=True, db_column='Days', null=True)),
                ('stime', models.TextField(blank=True, db_column='STime', null=True)),
                ('etime', models.TextField(blank=True, db_column='ETime', null=True)),
                ('bldg', models.TextField(blank=True, db_column='Bldg', null=True)),
                ('room', models.TextField(blank=True, db_column='Room', null=True)),
                ('sdate', models.TextField(blank=True, db_column='SDate', null=True)),
                ('edate', models.TextField(blank=True, db_column='EDate', null=True)),
                ('instructor', models.TextField(blank=True, db_column='Instructor', null=True)),
                ('aprv', models.TextField(blank=True, db_column='Aprv', null=True)),
                ('cap', models.TextField(blank=True, db_column='Cap', null=True)),
                ('enr', models.TextField(blank=True, db_column='Enr', null=True)),
                ('wait_max', models.TextField(blank=True, db_column='Wait Max', null=True)),
                ('wait', models.TextField(blank=True, db_column='Wait', null=True)),
                ('attn', models.TextField(blank=True, db_column='Attn', null=True)),
                ('attr', models.TextField(blank=True, db_column='Attr', null=True)),
                ('xst', models.TextField(blank=True, db_column='XST', null=True)),
                ('web', models.TextField(blank=True, db_column='Web', null=True)),
                ('sess_code', models.TextField(blank=True, db_column='Sess Code', null=True)),
                ('del_mthd', models.TextField(blank=True, db_column='Del Mthd', null=True)),
                ('pacing', models.TextField(blank=True, db_column='Pacing', null=True)),
                ('mtg_times', models.TextField(blank=True, db_column='Mtg Times', null=True)),
                ('site', models.TextField(blank=True, db_column='Site', null=True)),
                ('sec_notes', models.TextField(blank=True, db_column='Sec Notes', null=True)),
                ('tuiw', models.TextField(blank=True, db_column='TUIW', null=True)),
                ('code1', models.TextField(blank=True, db_column='Code1', null=True)),
                ('fee1', models.TextField(blank=True, db_column='Fee1', null=True)),
                ('code2', models.TextField(blank=True, db_column='Code2', null=True)),
                ('fee2', models.TextField(blank=True, db_column='Fee2', null=True)),
                ('code3', models.TextField(blank=True, db_column='Code3', null=True)),
                ('fee3', models.TextField(blank=True, db_column='Fee3', null=True)),
                ('code4', models.TextField(blank=True, db_column='Code4', null=True)),
                ('fee4', models.TextField(blank=True, db_column='Fee4', null=True)),
                ('code5', models.TextField(blank=True, db_column='Code5', null=True)),
                ('fee5', models.TextField(blank=True, db_column='Fee5', null=True)),
                ('code6', models.TextField(blank=True, db_column='Code6', null=True)),
                ('fee6', models.TextField(blank=True, db_column='Fee6', null=True)),
                ('code7', models.TextField(blank=True, db_column='Code7', null=True)),
                ('fee7', models.TextField(blank=True, db_column='Fee7', null=True)),
                ('code8', models.TextField(blank=True, db_column='Code8', null=True)),
                ('fee8', models.TextField(blank=True, db_column='Fee8', null=True)),
                ('code9', models.TextField(blank=True, db_column='Code9', null=True)),
                ('fee9', models.TextField(blank=True, db_column='Fee9', null=True)),
                ('code10', models.TextField(blank=True, db_column='Code10', null=True)),
                ('fee10', models.TextField(blank=True, db_column='Fee10', null=True)),
                ('code11', models.TextField(blank=True, db_column='Code11', null=True)),
                ('fee11', models.TextField(blank=True, db_column='Fee11', null=True)),
                ('code12', models.TextField(blank=True, db_column='Code12', null=True)),
                ('fee12', models.TextField(blank=True, db_column='Fee12', null=True)),
                ('uaonlinelink', models.TextField(blank=True, db_column='UAOnlineLink', null=True)),
                ('subject', models.TextField(blank=True, db_column='Subject', null=True)),
                ('course', models.TextField(blank=True, db_column='Course', null=True)),
                ('section', models.TextField(blank=True, db_column='Section', null=True)),
            ],
            options={
                'db_table': 'class_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassPrereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, db_column='Subject', null=True)),
                ('course', models.TextField(blank=True, db_column='Course', null=True)),
            ],
            options={
                'db_table': 'class_prereq',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='class_data',
        ),
        migrations.DeleteModel(
            name='class_prereq',
        ),
    ]
